// <auto-generated />
using FinRust.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinRust.Persistence.Migrations
{
    [DbContext(typeof(FinRustDbContext))]
    [Migration("20201130103422_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinRust.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int")
                        .HasMaxLength(5);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FinRust.Domain.Entities.Visualization", b =>
                {
                    b.Property<int>("VisualizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VisualizationID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("VisualizationId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Visualizations");
                });

            modelBuilder.Entity("FinRust.Domain.Entities.Visualization", b =>
                {
                    b.HasOne("FinRust.Domain.Entities.Customer", "Customer")
                        .WithMany("Visualizations")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Customer_Visualizations")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
